import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const read = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const schema = read("prisma/schema.prisma");
const migration = read("prisma/migrations/20260728170000_account_deletion_recovery/migration.sql");
const service = read("src/lib/account-deletion-service.ts");
const contract = read("src/lib/mobile-account-deletion-contract.ts");
const route = read("src/app/api/mobile/v1/account/deletion/route.ts");
const verificationRoute = read("src/app/api/mobile/v1/account/deletion/verification/route.ts");
const statusRoute = read("src/app/api/mobile/v1/account/deletion/status/route.ts");
const workerRoute = read("src/app/api/internal/account-deletion-worker/route.ts");
const admin = read("src/lib/supabase/admin.ts");

assert.match(schema, /model AccountDeletionRequest/);
assert.match(schema, /model AccountDeletionEmailOutbox/);
assert.match(schema, /operationReceiptHash/);
assert.match(schema, /executionLeaseExpiresAt/);
assert.match(schema, /purgeAfter/);
assert.match(schema, /DELETION_PENDING/);
assert.match(migration, /ALTER TABLE "AccountDeletionRequest"/);
assert.match(migration, /CREATE TABLE "AccountDeletionEmailOutbox"/);
assert.match(contract, /idempotencyKey: z\.string\(\)\.uuid\(\)/);
assert.match(contract, /deletionStatusSchema/);
assert.match(contract, /randomBytes\(32\)/);
assert.match(contract, /createHash\("sha256"\)/);
assert.match(service, /verificationAttempts >= maxVerificationAttempts/);
assert.match(service, /resendCount >= maxResends/);
assert.match(service, /Prisma\.TransactionIsolationLevel\.Serializable/);
assert.match(service, /updateMany\(/);
assert.match(service, /executionLeaseId/);
assert.match(service, /runAccountDeletionWorker/);
assert.match(service, /accountDeletionEmailOutbox/);
assert.match(service, /markDeletionRetryable\(requestId, leaseId, "AUTH_CONFIGURATION", "AUTH_DELETE_RETRY"\)/);
assert.match(service, /stage: \{ in: \["VERIFIED", "STORAGE_PENDING", "DATABASE_PENDING", "AUTH_PENDING", "AUTH_DELETE_RETRY", "FAILED_RETRYABLE"\] \}/);
assert.match(service, /legalHold/);
assert.match(service, /markDeletionRetryable/);
assert.match(service, /admin\.auth\.admin\.deleteUser/);
assert.match(service, /sendAccountDeletionCompletedEmail/);
assert.match(service, /userId: null, vehicleId: null, participantCode: null, qrTokenHash: null/);
assert.match(service, /payment\.deleteMany/);
assert.match(service, /providerMessageId: null/);
assert.match(admin, /import "server-only"/);
assert.match(admin, /SUPABASE_SERVICE_ROLE_KEY/);
assert.doesNotMatch(route, /body\.userId|body\.email/i);
assert.doesNotMatch(verificationRoute, /body\.userId|body\.email/i);
assert.doesNotMatch(service, /console\.(?:log|warn|error)\([^)]*(?:authUserId|email|verificationCode|imagePath)/i);
assert.match(service, /idempotencyKeyHash: null/); // Required only as the compare-and-set precondition.
assert.doesNotMatch(service, /data:\s*\{[\s\S]{0,200}idempotencyKeyHash:\s*null/);
assert.doesNotMatch(route, /export async function GET/);
assert.match(statusRoute, /deletionStatusSchema/);
assert.doesNotMatch(statusRoute, /authenticateMobileIdentity/);
assert.match(workerRoute, /CRON_SECRET/);
console.log("validate-account-deletion passed (34 assertions)");
