import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const read = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const schema = read("prisma/schema.prisma");
const migration = read("prisma/migrations/20260728170000_account_deletion_recovery/migration.sql");
const reservationMigration = read("prisma/migrations/20260728200000_account_deletion_side_effect_reservations/migration.sql");
const service = read("src/lib/account-deletion-service.ts");
const contract = read("src/lib/mobile-account-deletion-contract.ts");
const route = read("src/app/api/mobile/v1/account/deletion/route.ts");
const verificationRoute = read("src/app/api/mobile/v1/account/deletion/verification/route.ts");
const statusRoute = read("src/app/api/mobile/v1/account/deletion/status/route.ts");
const workerRoute = read("src/app/api/internal/account-deletion-worker/route.ts");
const admin = read("src/lib/supabase/admin.ts");
const releaseNote = read("docs/account-deletion-release.md");

assert.match(schema, /model AccountDeletionRequest/);
assert.match(schema, /model AccountDeletionEmailOutbox/);
assert.match(schema, /operationReceiptHash/);
assert.match(schema, /executionLeaseExpiresAt/);
assert.match(schema, /storageReservationId/);
assert.match(schema, /authReservationId/);
assert.match(schema, /deliveryReservationId/);
assert.match(schema, /purgeAfter/);
assert.match(schema, /DELETION_PENDING/);
assert.match(migration, /ALTER TABLE "AccountDeletionRequest"/);
assert.match(migration, /CREATE TABLE "AccountDeletionEmailOutbox"/);
assert.match(reservationMigration, /storageReservationId/);
assert.match(reservationMigration, /deliveryReservationId/);
assert.match(contract, /idempotencyKey: z\.string\(\)\.uuid\(\)/);
assert.match(contract, /deletionStatusSchema/);
assert.match(contract, /randomBytes\(32\)/);
assert.match(contract, /createHash\("sha256"\)/);
assert.match(service, /verificationAttempts >= maxVerificationAttempts/);
assert.match(service, /resendCount >= maxResends/);
assert.match(service, /Prisma\.TransactionIsolationLevel\.Serializable/);
assert.match(service, /updateMany\(/);
assert.match(service, /executionLeaseId/);
assert.match(service, /runAccountDeletionWorker/);
assert.match(service, /accountDeletionEmailOutbox/);
assert.match(service, /markDeletionRetryable\(requestId, lease, "AUTH_CONFIGURATION", "AUTH_DELETE_RETRY", clock\)/);
assert.match(service, /stage: \{ in: \["VERIFIED", "STORAGE_PENDING", "DATABASE_PENDING", "AUTH_PENDING", "AUTH_DELETE_RETRY", "FAILED_RETRYABLE"\] \}/);
assert.match(service, /legalHold/);
assert.match(service, /executionLeaseExpiresAt: \{ gt: now \}/);
assert.match(service, /operationVersion: lease\.operationVersion/);
assert.match(service, /renewDeletionLease/);
assert.match(service, /reserveRequestSideEffect/);
assert.match(service, /setAccountDeletionLegalHold/);
assert.match(service, /COMMIT_POINT_PASSED/);
assert.match(service, /afterStorageReservationBeforeAdapter/);
assert.match(service, /afterAuthReservationBeforeAdapter/);
assert.match(service, /afterCompletionEmailReservationBeforeAdapter/);
assert.doesNotMatch(service, /for \(const \[key, entry\] of receiptStatusAttempts\)/);
assert.match(service, /activeDeletionWhere/);
assert.match(service, /receiptStatusMaxEntries/);
assert.match(service, /markDeletionRetryable/);
assert.match(service, /admin\.auth\.admin\.deleteUser/);
assert.match(service, /sendAccountDeletionCompletedEmail/);
assert.match(service, /userId: null, vehicleId: null, participantCode: null, qrTokenHash: null/);
assert.match(service, /payment\.deleteMany/);
assert.match(service, /providerMessageId: null/);
assert.match(admin, /import "server-only"/);
assert.match(admin, /SUPABASE_SERVICE_ROLE_KEY/);
assert.doesNotMatch(route, /body\.userId|body\.email/i);
assert.doesNotMatch(verificationRoute, /body\.userId|body\.email/i);
assert.doesNotMatch(service, /console\.(?:log|warn|error)\([^)]*(?:authUserId|email|verificationCode|imagePath)/i);
assert.match(service, /idempotencyKeyHash: null/); // Required only as the compare-and-set precondition.
assert.doesNotMatch(service, /data:\s*\{[\s\S]{0,200}idempotencyKeyHash:\s*null/);
assert.doesNotMatch(route, /export async function GET/);
assert.match(statusRoute, /deletionStatusSchema/);
assert.doesNotMatch(statusRoute, /authenticateMobileIdentity/);
assert.match(workerRoute, /CRON_SECRET/);
assert.doesNotMatch(migration, /AccountDeletionRequest_operationReceiptHash_idx/);
assert.doesNotMatch(schema, /@@index\(\[operationReceiptHash\]\)/);
assert.match(releaseNote, /first-release contract/);
assert.match(releaseNote, /no checked-in\s+evidence of an installed legacy mobile client/);
assert.match(releaseNote, /must be released in order:/);
assert.match(releaseNote, /not a compatibility fallback/);
assert.match(releaseNote, /COMMIT_POINT_PASSED/);
console.log("validate-account-deletion passed (44 assertions)");
